import React, { useState, useMemo, useEffect } from 'react';
import ServiceCentreFinder from './ServiceCentreFinder';

// ─── Configurable Samsung Support Resources by country code ───
const SAMSUNG_SUPPORT_URLS = {
  IN: {
    code: 'IN',
    label: 'Samsung India Support',
    countryName: 'India',
    flag: '🇮🇳',
    email: 'support.india@samsung.com',
    contact: 'https://www.samsung.com/in/support/',
    serviceCentre: 'https://www.samsung.com/in/support/service-center/',
    chat: 'https://www.samsung.com/in/support/livechat/',
    tollFree: '1800 40 7267864 (1800 40 SAMSUNG)',
  },
  US: {
    code: 'US',
    label: 'Samsung US Support',
    countryName: 'United States',
    flag: '🇺🇸',
    email: 'support@samsung.com',
    contact: 'https://www.samsung.com/us/support/',
    serviceCentre: 'https://www.samsung.com/us/support/service-center/',
    chat: 'https://www.samsung.com/us/support/livechat/',
    tollFree: '1-800-SAMSUNG (726-7864)',
  },
  GB: {
    code: 'GB',
    label: 'Samsung UK Support',
    countryName: 'United Kingdom',
    flag: '🇬🇧',
    email: 'uk.customercare@samsung.com',
    contact: 'https://www.samsung.com/uk/support/',
    serviceCentre: 'https://www.samsung.com/uk/support/service-center/',
    chat: 'https://www.samsung.com/uk/support/livechat/',
    tollFree: '0333 000 0333',
  },
  GLOBAL: {
    code: 'GLOBAL',
    label: 'Samsung Global Support',
    countryName: 'Global',
    flag: '🌐',
    email: 'support@samsung.com',
    contact: 'https://www.samsung.com/support/',
    serviceCentre: 'https://www.samsung.com/support/service-center/',
    chat: null,
    tollFree: null,
  },
};

function detectCountryCode() {
  try {
    // 1. Timezone detection (most reliable for India & specific regions)
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone || '';
    if (tz.includes('Kolkata') || tz.includes('Calcutta') || tz.includes('Asia/Colombo')) {
      return 'IN';
    }
    const offset = new Date().getTimezoneOffset();
    if (offset === -330) {
      // UTC+5:30 -> India
      return 'IN';
    }

    // 2. Locale detection
    const locale = navigator.language || navigator.userLanguage || '';
    const parts = locale.split('-');
    const country = (parts[1] || '').toUpperCase();
    if (SAMSUNG_SUPPORT_URLS[country]) {
      return country;
    }
  } catch {
    // ignore
  }
  return 'IN'; // Default to India for Samsung PRISM Hackathon context
}

function formatTimestamp() {
  return new Date().toISOString().replace('T', ' ').substring(0, 19) + ' UTC';
}

// ─── Build report text from session data ───
function buildReportText(result, query, sessionId) {
  const lines = [];
  lines.push('═══════════════════════════════════════════════');
  lines.push('  SAMSUNG PRISM TROUBLESHOOTING REPORT');
  lines.push('═══════════════════════════════════════════════');
  lines.push('');
  lines.push(`Generated: ${formatTimestamp()}`);
  if (sessionId) lines.push(`Session Reference: ${sessionId}`);
  lines.push(`Engine Version: PRISM v5.1`);
  lines.push('');

  lines.push('─── ISSUE DESCRIPTION ───');
  lines.push(query || 'Not provided');
  lines.push('');

  if (result.domain) {
    lines.push('─── DIAGNOSIS SUMMARY ───');
    lines.push(`Domain: ${result.domain}`);
    if (result.issue) lines.push(`Issue: ${result.issue}`);
    if (result.title) lines.push(`Title: ${result.title}`);
    const conf = result.final_confidence || result.confidence;
    if (conf) lines.push(`Confidence: ${(conf * 100).toFixed(1)}%`);
    if (result.source) lines.push(`Source: ${result.source}`);
    lines.push('');
  }

  if (result.steps && result.steps.length > 0) {
    lines.push('─── RECOMMENDED STEPS ATTEMPTED ───');
    result.steps.forEach((step, idx) => {
      lines.push(`  ${idx + 1}. ${step}`);
    });
    lines.push('');
  }

  lines.push('─── USER OUTCOME ───');
  lines.push('Status: Issue persists after applying all recommended steps.');
  lines.push('');

  if (result.source) {
    lines.push('─── REFERENCE DOCUMENTATION ───');
    lines.push(`Source: ${result.source}`);
    if (result.source_type) lines.push(`Type: ${result.source_type}`);
    lines.push('');
  }

  lines.push('─── NOTE ───');
  lines.push('This report was generated by Samsung PRISM Troubleshooting Engine.');
  lines.push('No sensitive device identifiers (IMEI, serial) are included.');
  lines.push('');
  lines.push('═══════════════════════════════════════════════');

  return lines.join('\n');
}

export default function EscalationPanel({ result, query, sessionId, onClose }) {
  const [activeView, setActiveView] = useState('menu'); // menu | contact | compose | centres | report
  const [selectedCountry, setSelectedCountry] = useState(detectCountryCode);
  const [reportCopied, setReportCopied] = useState(false);
  const [emailCopied, setEmailCopied] = useState(false);

  const supportConfig = useMemo(() => {
    return SAMSUNG_SUPPORT_URLS[selectedCountry] || SAMSUNG_SUPPORT_URLS.IN;
  }, [selectedCountry]);

  // Initial Email fields
  const [emailTo, setEmailTo] = useState('');
  const [emailSubject, setEmailSubject] = useState('');
  const [emailBody, setEmailBody] = useState('');

  // Synchronize email draft when supportConfig or result changes
  useEffect(() => {
    const to = supportConfig.email || 'support.india@samsung.com';
    const sub = `[Samsung Support Request] ${result.title || query || 'Device Issue'} - Issue Persists`;

    const bodyLines = [
      `Dear ${supportConfig.label} Team,`,
      '',
      'I am reaching out regarding a persistent technical issue on my Samsung device that was not resolved by following the verified troubleshooting protocol from the Samsung PRISM Troubleshooting Engine.',
      '',
      '─── ISSUE SUMMARY ───',
      `Reported Symptom: ${query || 'Not specified'}`,
      `Engine Diagnosis: ${result.title || 'General Anomaly'}`,
      `Category: ${result.domain || 'Device'}`,
      `Diagnostic Confidence: ${((result.final_confidence || result.confidence || 0.85) * 100).toFixed(1)}%`,
      `Session Reference: #${sessionId || 'PRISM-SEC-88219'}`,
      `Timestamp: ${formatTimestamp()}`,
      '',
      '─── TROUBLESHOOTING STEPS ALREADY ATTEMPTED ───',
      ...(result.steps && result.steps.length > 0
        ? result.steps.map((s, i) => `${i + 1}. ${s}`)
        : ['1. Standard device reboot and diagnostic check']),
      '',
      '─── CURRENT STATUS ───',
      'User Confirmation: The issue still persists on the device.',
      '',
      'Please advise on official service options, escalation to Samsung technical engineers, or warranty repair guidance.',
      '',
      'Sincerely,',
      'Samsung Galaxy User'
    ];

    setEmailTo(to);
    setEmailSubject(sub);
    setEmailBody(bodyLines.join('\n'));
  }, [supportConfig, result, query, sessionId]);

  const reportText = useMemo(
    () => buildReportText(result, query, sessionId),
    [result, query, sessionId]
  );

  // ─── Actions for Sending ───
  const openGmail = () => {
    const url = `https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(emailTo)}&su=${encodeURIComponent(emailSubject)}&body=${encodeURIComponent(emailBody)}`;
    window.open(url, '_blank', 'noopener,noreferrer');
  };

  const openOutlook = () => {
    const url = `https://outlook.live.com/owa/?path=/mail/action/compose&to=${encodeURIComponent(emailTo)}&subject=${encodeURIComponent(emailSubject)}&body=${encodeURIComponent(emailBody)}`;
    window.open(url, '_blank', 'noopener,noreferrer');
  };

  const openDefaultMail = () => {
    const url = `mailto:${encodeURIComponent(emailTo)}?subject=${encodeURIComponent(emailSubject)}&body=${encodeURIComponent(emailBody)}`;
    window.location.href = url;
  };

  const handleCopyEmail = async () => {
    const fullText = `To: ${emailTo}\nSubject: ${emailSubject}\n\n${emailBody}`;
    try {
      await navigator.clipboard.writeText(fullText);
      setEmailCopied(true);
      setTimeout(() => setEmailCopied(false), 2500);
    } catch {
      setEmailCopied(true);
      setTimeout(() => setEmailCopied(false), 2500);
    }
  };

  const handleCopyReport = async () => {
    try {
      await navigator.clipboard.writeText(reportText);
      setReportCopied(true);
      setTimeout(() => setReportCopied(false), 2500);
    } catch {
      setReportCopied(true);
      setTimeout(() => setReportCopied(false), 2500);
    }
  };

  const handleDownloadReport = () => {
    try {
      const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `samsung-prism-report-${Date.now()}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch {
      // ignore
    }
  };

  return (
    <div className="escalation-overlay" onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="escalation-panel" role="dialog" aria-modal="true" aria-label="Issue Escalation">
        {/* Header */}
        <div className="escalation-header">
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            {activeView !== 'menu' && (
              <button
                type="button"
                className="escalation-back-btn"
                onClick={() => {
                  if (activeView === 'compose') setActiveView('contact');
                  else setActiveView('menu');
                }}
                aria-label="Back"
              >
                <span className="material-symbols-outlined" style={{ fontSize: '20px' }}>arrow_back</span>
              </button>
            )}
            <div>
              <h2 className="escalation-title">
                {activeView === 'menu' && "Let's get this resolved"}
                {activeView === 'contact' && 'Contact Samsung Support'}
                {activeView === 'compose' && 'Compose & Send Support Email'}
                {activeView === 'centres' && 'Find a Service Centre'}
                {activeView === 'report' && 'Troubleshooting Report'}
              </h2>
              <p className="escalation-subtitle">
                {activeView === 'menu' && "The recommended steps didn't solve your issue. You can contact Samsung Support or find an authorized service centre."}
                {activeView === 'contact' && "Review the details below, choose your regional support portal, or compose an email."}
                {activeView === 'compose' && "Review and edit your support email, then send via Gmail, Outlook, or your preferred mail client."}
                {activeView === 'centres' && "Locate an official Samsung-authorized service centre near you."}
                {activeView === 'report' && "A summary of your troubleshooting session. Copy or download for reference."}
              </p>
            </div>
          </div>
          <button
            type="button"
            className="escalation-close-btn"
            onClick={onClose}
            aria-label="Close escalation panel"
          >
            <span className="material-symbols-outlined" style={{ fontSize: '22px' }}>close</span>
          </button>
        </div>

        {/* Body */}
        <div className="escalation-body">

          {/* ═══ MENU VIEW ═══ */}
          {activeView === 'menu' && (
            <div className="escalation-options">
              {/* Option A: Contact Support */}
              <button
                type="button"
                className="escalation-option-card"
                onClick={() => setActiveView('contact')}
              >
                <div className="escalation-option-icon" style={{ background: 'rgba(0, 240, 255, 0.12)', color: 'var(--primary)' }}>
                  <span className="material-symbols-outlined">support_agent</span>
                </div>
                <div className="escalation-option-content">
                  <h3>Contact Samsung Support</h3>
                  <p>Get help from Samsung's official support team via website, chat, or email.</p>
                </div>
                <span className="material-symbols-outlined escalation-option-arrow">chevron_right</span>
              </button>

              {/* Option B: Service Centre */}
              <button
                type="button"
                className="escalation-option-card"
                onClick={() => setActiveView('centres')}
              >
                <div className="escalation-option-icon" style={{ background: 'rgba(56, 189, 248, 0.12)', color: 'var(--secondary)' }}>
                  <span className="material-symbols-outlined">location_on</span>
                </div>
                <div className="escalation-option-content">
                  <h3>Find a Nearby Service Centre</h3>
                  <p>Locate an official Samsung-authorized service centre for in-person repairs.</p>
                </div>
                <span className="material-symbols-outlined escalation-option-arrow">chevron_right</span>
              </button>

              {/* Option C: Report */}
              <button
                type="button"
                className="escalation-option-card"
                onClick={() => setActiveView('report')}
              >
                <div className="escalation-option-icon" style={{ background: 'rgba(16, 185, 129, 0.12)', color: 'var(--success)' }}>
                  <span className="material-symbols-outlined">description</span>
                </div>
                <div className="escalation-option-content">
                  <h3>Generate Troubleshooting Report</h3>
                  <p>Download a summary of this diagnostic session to share with support or technicians.</p>
                </div>
                <span className="material-symbols-outlined escalation-option-arrow">chevron_right</span>
              </button>
            </div>
          )}

          {/* ═══ CONTACT VIEW ═══ */}
          {activeView === 'contact' && (
            <div className="escalation-contact">
              {/* Region Selector Pills */}
              <div className="country-selector-box">
                <span className="country-selector-label">
                  <span className="material-symbols-outlined" style={{ fontSize: '15px' }}>public</span>
                  <span>Select Region:</span>
                </span>
                <div className="country-pills-row">
                  {Object.keys(SAMSUNG_SUPPORT_URLS).map((code) => {
                    const cfg = SAMSUNG_SUPPORT_URLS[code];
                    const isSelected = selectedCountry === code;
                    return (
                      <button
                        key={code}
                        type="button"
                        className={`country-pill ${isSelected ? 'active' : ''}`}
                        onClick={() => setSelectedCountry(code)}
                      >
                        <span>{cfg.flag}</span>
                        <span>{cfg.countryName}</span>
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* Report Preview */}
              <div className="escalation-report-preview">
                <div className="escalation-report-label">
                  <span className="material-symbols-outlined" style={{ fontSize: '15px' }}>info</span>
                  <span>Information that will be shared</span>
                </div>
                <div className="escalation-report-items">
                  {query && (
                    <div className="escalation-report-item">
                      <span className="escalation-report-item-label">Issue</span>
                      <span className="escalation-report-item-value">{query}</span>
                    </div>
                  )}
                  {result.title && (
                    <div className="escalation-report-item">
                      <span className="escalation-report-item-label">Diagnosis</span>
                      <span className="escalation-report-item-value">{result.title}</span>
                    </div>
                  )}
                  {result.domain && (
                    <div className="escalation-report-item">
                      <span className="escalation-report-item-label">Category</span>
                      <span className="escalation-report-item-value">{result.domain}</span>
                    </div>
                  )}
                  {result.steps && result.steps.length > 0 && (
                    <div className="escalation-report-item">
                      <span className="escalation-report-item-label">Steps tried</span>
                      <span className="escalation-report-item-value">{result.steps.length} steps attempted</span>
                    </div>
                  )}
                  <div className="escalation-report-item">
                    <span className="escalation-report-item-label">Outcome</span>
                    <span className="escalation-report-item-value" style={{ color: 'var(--error)' }}>Issue persists</span>
                  </div>
                </div>
                <p style={{ fontSize: '11px', color: 'var(--on-surface-variant)', marginTop: '8px', fontFamily: 'var(--font-mono)' }}>
                  No IMEI, serial numbers, or authentication tokens are included.
                </p>
              </div>

              {/* Action Buttons */}
              <div className="escalation-contact-actions">
                <button
                  type="button"
                  className="escalation-action-btn primary"
                  onClick={() => setActiveView('compose')}
                >
                  <span className="material-symbols-outlined" style={{ fontSize: '18px' }}>mail</span>
                  <span>Compose & Send Email</span>
                </button>

                <a
                  href={supportConfig.contact}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="escalation-action-btn secondary"
                >
                  <span className="material-symbols-outlined" style={{ fontSize: '18px' }}>open_in_new</span>
                  <span>Open {supportConfig.label}</span>
                </a>

                {supportConfig.chat && (
                  <a
                    href={supportConfig.chat}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="escalation-action-btn secondary"
                  >
                    <span className="material-symbols-outlined" style={{ fontSize: '18px' }}>chat</span>
                    <span>Live Chat</span>
                  </a>
                )}
              </div>

              <div className="support-info-footer">
                <span className="material-symbols-outlined" style={{ fontSize: '15px', color: 'var(--primary)' }}>help</span>
                <span>
                  Clicking <strong>Compose & Send Email</strong> lets you preview and send the report via <strong>Gmail</strong>, <strong>Outlook Web</strong>, or your <strong>default mail app</strong>.
                </span>
              </div>
            </div>
          )}

          {/* ═══ COMPOSE & SEND VIEW ═══ */}
          {activeView === 'compose' && (
            <div className="escalation-compose-view">
              <div className="compose-field">
                <label className="compose-label">To (Official Support Email):</label>
                <input
                  type="email"
                  className="compose-input"
                  value={emailTo}
                  onChange={(e) => setEmailTo(e.target.value)}
                  placeholder="recipient@samsung.com"
                />
              </div>

              <div className="compose-field">
                <label className="compose-label">Subject:</label>
                <input
                  type="text"
                  className="compose-input"
                  value={emailSubject}
                  onChange={(e) => setEmailSubject(e.target.value)}
                  placeholder="Subject line"
                />
              </div>

              <div className="compose-field">
                <label className="compose-label">Message Content (Editable):</label>
                <textarea
                  className="compose-textarea"
                  rows={8}
                  value={emailBody}
                  onChange={(e) => setEmailBody(e.target.value)}
                />
              </div>

              {/* Action Buttons to Dispatch */}
              <div className="compose-actions-grid">
                <button
                  type="button"
                  className="escalation-action-btn primary"
                  onClick={openGmail}
                  title="Open in Gmail Webmail with pre-filled To, Subject, and Body"
                >
                  <span className="material-symbols-outlined" style={{ fontSize: '18px' }}>outgoing_mail</span>
                  <span>Send via Gmail</span>
                </button>

                <button
                  type="button"
                  className="escalation-action-btn secondary"
                  onClick={openOutlook}
                  title="Open in Outlook Webmail with pre-filled message"
                >
                  <span className="material-symbols-outlined" style={{ fontSize: '18px' }}>mail</span>
                  <span>Send via Outlook</span>
                </button>

                <button
                  type="button"
                  className="escalation-action-btn ghost"
                  onClick={openDefaultMail}
                  title="Trigger mailto: with your system default mail client"
                >
                  <span className="material-symbols-outlined" style={{ fontSize: '18px' }}>mark_email_read</span>
                  <span>Open System Mail</span>
                </button>

                <button
                  type="button"
                  className="escalation-action-btn ghost"
                  onClick={handleCopyEmail}
                >
                  <span className="material-symbols-outlined" style={{ fontSize: '18px' }}>
                    {emailCopied ? 'check' : 'content_copy'}
                  </span>
                  <span>{emailCopied ? 'Copied Full Draft!' : 'Copy Full Draft'}</span>
                </button>
              </div>

              <p style={{ fontSize: '11px', color: 'var(--on-surface-variant)', marginTop: '8px', lineHeight: '16px' }}>
                💡 Tip: If you don't have a desktop email client configured on Windows, click <strong>"Send via Gmail"</strong> or <strong>"Copy Full Draft"</strong> to paste into your favorite mail app.
              </p>
            </div>
          )}

          {/* ═══ SERVICE CENTRES VIEW ═══ */}
          {activeView === 'centres' && (
            <ServiceCentreFinder supportConfig={supportConfig} />
          )}

          {/* ═══ REPORT VIEW ═══ */}
          {activeView === 'report' && (
            <div className="escalation-report">
              <pre className="escalation-report-text">{reportText}</pre>
              <div className="escalation-report-actions">
                <button
                  type="button"
                  className="escalation-action-btn primary"
                  onClick={handleCopyReport}
                >
                  <span className="material-symbols-outlined" style={{ fontSize: '20px' }}>
                    {reportCopied ? 'check' : 'content_copy'}
                  </span>
                  <span>{reportCopied ? 'Copied!' : 'Copy Report'}</span>
                </button>
                <button
                  type="button"
                  className="escalation-action-btn secondary"
                  onClick={handleDownloadReport}
                >
                  <span className="material-symbols-outlined" style={{ fontSize: '20px' }}>download</span>
                  <span>Download as .txt</span>
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
