import React, { useState, useMemo } from 'react';
import ServiceCentreFinder from './ServiceCentreFinder';

// ─── Configurable Samsung Support URLs by country code ───
const SAMSUNG_SUPPORT_URLS = {
  IN: {
    label: 'Samsung India Support',
    contact: 'https://www.samsung.com/in/support/',
    serviceCentre: 'https://www.samsung.com/in/support/service-center/',
    chat: 'https://www.samsung.com/in/support/livechat/',
  },
  US: {
    label: 'Samsung US Support',
    contact: 'https://www.samsung.com/us/support/',
    serviceCentre: 'https://www.samsung.com/us/support/service-center/',
    chat: 'https://www.samsung.com/us/support/livechat/',
  },
  GB: {
    label: 'Samsung UK Support',
    contact: 'https://www.samsung.com/uk/support/',
    serviceCentre: 'https://www.samsung.com/uk/support/service-center/',
  },
  // Fallback / global
  GLOBAL: {
    label: 'Samsung Global Support',
    contact: 'https://www.samsung.com/support/',
    serviceCentre: 'https://www.samsung.com/support/service-center/',
  },
};

function getSupportConfig() {
  // Attempt to detect country from browser locale
  try {
    const locale = navigator.language || navigator.userLanguage || '';
    const parts = locale.split('-');
    const countryCode = (parts[1] || parts[0] || '').toUpperCase();
    if (SAMSUNG_SUPPORT_URLS[countryCode]) {
      return SAMSUNG_SUPPORT_URLS[countryCode];
    }
    // Check timezone as fallback for India
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone || '';
    if (tz.startsWith('Asia/Kolkata') || tz.startsWith('Asia/Calcutta')) {
      return SAMSUNG_SUPPORT_URLS.IN;
    }
  } catch {
    // ignore
  }
  return SAMSUNG_SUPPORT_URLS.GLOBAL;
}

function formatTimestamp() {
  return new Date().toISOString().replace('T', ' ').substring(0, 19) + ' UTC';
}

// ─── Build report text from session data ───
function buildReportText(result, query, sessionId) {
  const lines = [];
  lines.push('═══════════════════════════════════════════════');
  lines.push('  SAMSUNG PRISM TROUBLESHOOTING REPORT');
  lines.push('═══════════════════════════════════════════════');
  lines.push('');
  lines.push(`Generated: ${formatTimestamp()}`);
  if (sessionId) lines.push(`Session Reference: ${sessionId}`);
  lines.push(`Engine Version: PRISM v5.1`);
  lines.push('');

  lines.push('─── ISSUE DESCRIPTION ───');
  lines.push(query || 'Not provided');
  lines.push('');

  if (result.domain) {
    lines.push('─── DIAGNOSIS SUMMARY ───');
    lines.push(`Domain: ${result.domain}`);
    if (result.issue) lines.push(`Issue: ${result.issue}`);
    if (result.title) lines.push(`Title: ${result.title}`);
    const conf = result.final_confidence || result.confidence;
    if (conf) lines.push(`Confidence: ${(conf * 100).toFixed(1)}%`);
    if (result.source) lines.push(`Source: ${result.source}`);
    lines.push('');
  }

  if (result.steps && result.steps.length > 0) {
    lines.push('─── RECOMMENDED STEPS ───');
    result.steps.forEach((step, idx) => {
      lines.push(`  ${idx + 1}. ${step}`);
    });
    lines.push('');
  }

  lines.push('─── USER OUTCOME ───');
  lines.push('Status: Issue persists after attempting recommended steps.');
  lines.push('');

  if (result.source) {
    lines.push('─── REFERENCE DOCUMENTATION ───');
    lines.push(`Source: ${result.source}`);
    if (result.source_type) lines.push(`Type: ${result.source_type}`);
    lines.push('');
  }

  lines.push('─── NOTE ───');
  lines.push('This report was generated by Samsung PRISM Troubleshooting Engine.');
  lines.push('No sensitive device identifiers (IMEI, serial) are included.');
  lines.push('');
  lines.push('═══════════════════════════════════════════════');

  return lines.join('\n');
}


export default function EscalationPanel({ result, query, sessionId, onClose }) {
  const [activeView, setActiveView] = useState('menu'); // menu | contact | centres | report
  const [reportCopied, setReportCopied] = useState(false);

  const supportConfig = useMemo(() => getSupportConfig(), []);

  const reportText = useMemo(
    () => buildReportText(result, query, sessionId),
    [result, query, sessionId]
  );

  // ─── Contact Support: build mailto body ───
  const mailtoBody = useMemo(() => {
    const lines = [];
    lines.push('Dear Samsung Support,');
    lines.push('');
    lines.push('I am experiencing an issue with my Samsung device that persists after following the recommended troubleshooting steps from the PRISM Diagnostic Engine.');
    lines.push('');
    if (query) {
      lines.push(`Issue Description: ${query}`);
      lines.push('');
    }
    if (result.title) {
      lines.push(`Diagnosis: ${result.title}`);
    }
    if (result.domain) {
      lines.push(`Category: ${result.domain}`);
    }
    if (result.steps && result.steps.length > 0) {
      lines.push('');
      lines.push('Steps already attempted:');
      result.steps.forEach((step, idx) => {
        lines.push(`  ${idx + 1}. ${step}`);
      });
    }
    lines.push('');
    lines.push('The issue still persists. Please advise on next steps or arrange a service appointment.');
    lines.push('');
    lines.push('Thank you.');
    return encodeURIComponent(lines.join('\n'));
  }, [result, query]);

  const mailtoSubject = useMemo(() => {
    const title = result.title || query || 'Device Issue';
    return encodeURIComponent(`Samsung Device Issue: ${title}`);
  }, [result, query]);

  // ─── Copy report ───
  const handleCopyReport = async () => {
    try {
      await navigator.clipboard.writeText(reportText);
      setReportCopied(true);
      setTimeout(() => setReportCopied(false), 2500);
    } catch {
      // Fallback: select text
      setReportCopied(true);
      setTimeout(() => setReportCopied(false), 2500);
    }
  };

  // ─── Download report ───
  const handleDownloadReport = () => {
    try {
      const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `samsung-prism-report-${Date.now()}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch {
      // If download fails, the user can still copy
    }
  };

  return (
    <div className="escalation-overlay" onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="escalation-panel" role="dialog" aria-modal="true" aria-label="Issue Escalation">
        {/* Header */}
        <div className="escalation-header">
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            {activeView !== 'menu' && (
              <button
                type="button"
                className="escalation-back-btn"
                onClick={() => setActiveView('menu')}
                aria-label="Back to escalation menu"
              >
                <span className="material-symbols-outlined" style={{ fontSize: '20px' }}>arrow_back</span>
              </button>
            )}
            <div>
              <h2 className="escalation-title">
                {activeView === 'menu' && "Let's get this resolved"}
                {activeView === 'contact' && 'Contact Samsung Support'}
                {activeView === 'centres' && 'Find a Service Centre'}
                {activeView === 'report' && 'Troubleshooting Report'}
              </h2>
              <p className="escalation-subtitle">
                {activeView === 'menu' && "The recommended steps didn't solve your issue. You can contact Samsung Support or find an authorized service centre."}
                {activeView === 'contact' && "Review the details below, then open Samsung's official support page or compose a support email."}
                {activeView === 'centres' && "Locate an official Samsung-authorized service centre near you."}
                {activeView === 'report' && "A summary of your troubleshooting session. Copy or download for reference."}
              </p>
            </div>
          </div>
          <button
            type="button"
            className="escalation-close-btn"
            onClick={onClose}
            aria-label="Close escalation panel"
          >
            <span className="material-symbols-outlined" style={{ fontSize: '22px' }}>close</span>
          </button>
        </div>

        {/* Body */}
        <div className="escalation-body">

          {/* ═══ MENU VIEW ═══ */}
          {activeView === 'menu' && (
            <div className="escalation-options">
              {/* Option A: Contact Support */}
              <button
                type="button"
                className="escalation-option-card"
                onClick={() => setActiveView('contact')}
              >
                <div className="escalation-option-icon" style={{ background: 'rgba(124, 58, 237, 0.15)', color: 'var(--primary)' }}>
                  <span className="material-symbols-outlined">support_agent</span>
                </div>
                <div className="escalation-option-content">
                  <h3>Contact Samsung Support</h3>
                  <p>Get help from Samsung's official support team via their website or email.</p>
                </div>
                <span className="material-symbols-outlined escalation-option-arrow">chevron_right</span>
              </button>

              {/* Option B: Service Centre */}
              <button
                type="button"
                className="escalation-option-card"
                onClick={() => setActiveView('centres')}
              >
                <div className="escalation-option-icon" style={{ background: 'rgba(76, 215, 246, 0.15)', color: 'var(--tertiary)' }}>
                  <span className="material-symbols-outlined">location_on</span>
                </div>
                <div className="escalation-option-content">
                  <h3>Find a Nearby Service Centre</h3>
                  <p>Locate an official Samsung-authorized service centre for in-person repairs.</p>
                </div>
                <span className="material-symbols-outlined escalation-option-arrow">chevron_right</span>
              </button>

              {/* Option C: Report */}
              <button
                type="button"
                className="escalation-option-card"
                onClick={() => setActiveView('report')}
              >
                <div className="escalation-option-icon" style={{ background: 'rgba(16, 185, 129, 0.15)', color: 'var(--success)' }}>
                  <span className="material-symbols-outlined">description</span>
                </div>
                <div className="escalation-option-content">
                  <h3>Generate Troubleshooting Report</h3>
                  <p>Download a summary of this diagnostic session to share with support or technicians.</p>
                </div>
                <span className="material-symbols-outlined escalation-option-arrow">chevron_right</span>
              </button>
            </div>
          )}

          {/* ═══ CONTACT VIEW ═══ */}
          {activeView === 'contact' && (
            <div className="escalation-contact">
              {/* Report Preview */}
              <div className="escalation-report-preview">
                <div className="escalation-report-label">
                  <span className="material-symbols-outlined" style={{ fontSize: '16px' }}>info</span>
                  <span>Information that will be shared</span>
                </div>
                <div className="escalation-report-items">
                  {query && (
                    <div className="escalation-report-item">
                      <span className="escalation-report-item-label">Issue</span>
                      <span className="escalation-report-item-value">{query}</span>
                    </div>
                  )}
                  {result.title && (
                    <div className="escalation-report-item">
                      <span className="escalation-report-item-label">Diagnosis</span>
                      <span className="escalation-report-item-value">{result.title}</span>
                    </div>
                  )}
                  {result.domain && (
                    <div className="escalation-report-item">
                      <span className="escalation-report-item-label">Category</span>
                      <span className="escalation-report-item-value">{result.domain}</span>
                    </div>
                  )}
                  {result.steps && result.steps.length > 0 && (
                    <div className="escalation-report-item">
                      <span className="escalation-report-item-label">Steps tried</span>
                      <span className="escalation-report-item-value">{result.steps.length} steps attempted</span>
                    </div>
                  )}
                  <div className="escalation-report-item">
                    <span className="escalation-report-item-label">Outcome</span>
                    <span className="escalation-report-item-value" style={{ color: 'var(--error)' }}>Issue persists</span>
                  </div>
                </div>
                <p style={{ fontSize: '11px', color: 'var(--on-surface-variant)', marginTop: '8px', fontFamily: 'var(--font-mono)' }}>
                  No IMEI, serial numbers, or authentication tokens are included.
                </p>
              </div>

              {/* Action Buttons */}
              <div className="escalation-contact-actions">
                <a
                  href={supportConfig.contact}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="escalation-action-btn primary"
                >
                  <span className="material-symbols-outlined" style={{ fontSize: '20px' }}>open_in_new</span>
                  <span>Open {supportConfig.label}</span>
                </a>

                {supportConfig.chat && (
                  <a
                    href={supportConfig.chat}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="escalation-action-btn secondary"
                  >
                    <span className="material-symbols-outlined" style={{ fontSize: '20px' }}>chat</span>
                    <span>Live Chat</span>
                  </a>
                )}

                <a
                  href={`mailto:?subject=${mailtoSubject}&body=${mailtoBody}`}
                  className="escalation-action-btn ghost"
                >
                  <span className="material-symbols-outlined" style={{ fontSize: '20px' }}>mail</span>
                  <span>Compose Email Draft</span>
                </a>
              </div>

              <p style={{ fontSize: '12px', color: 'var(--on-surface-variant)', marginTop: '12px', lineHeight: '16px' }}>
                Clicking "Open {supportConfig.label}" will take you to Samsung's official support website.
                "Compose Email Draft" opens your default email app with a pre-filled message — no email is sent automatically.
              </p>
            </div>
          )}

          {/* ═══ SERVICE CENTRES VIEW ═══ */}
          {activeView === 'centres' && (
            <ServiceCentreFinder supportConfig={supportConfig} />
          )}

          {/* ═══ REPORT VIEW ═══ */}
          {activeView === 'report' && (
            <div className="escalation-report">
              <pre className="escalation-report-text">{reportText}</pre>
              <div className="escalation-report-actions">
                <button
                  type="button"
                  className="escalation-action-btn primary"
                  onClick={handleCopyReport}
                >
                  <span className="material-symbols-outlined" style={{ fontSize: '20px' }}>
                    {reportCopied ? 'check' : 'content_copy'}
                  </span>
                  <span>{reportCopied ? 'Copied!' : 'Copy Report'}</span>
                </button>
                <button
                  type="button"
                  className="escalation-action-btn secondary"
                  onClick={handleDownloadReport}
                >
                  <span className="material-symbols-outlined" style={{ fontSize: '20px' }}>download</span>
                  <span>Download as .txt</span>
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
